### ISSUE TITLE
tolerations issue in Helm

### ISSUE THREAD

**Issue by luoyimu1** [linki/cloudformation-operator#150]
Hi,
Under helm/c-o/templates/deployment.yaml, the tolerations section should be under spec (currently it's under containers), pls kindly help fix.

Also, is it possible to open the permission so we could create branches and raise PR?

Cheers,

**Comment by linki** [comment]
@luoyimu1 It's fixed on the latest master commit.

Regarding contributions, you can always fork the repo and propose PRs from your fork.
