### ISSUE TITLE
Is it maintained?

### ISSUE THREAD

**Issue by pierreozoux** [linki/cloudformation-operator#20]
And is it a personal project, or used in a professional context?

It looks nice, and trying to understand the level of effort that will be put there later on.
If I use it, I'll obviously help you then. (But it is not clear yet the direction we are taking in our company).

Basically, we need to provide RDS to our multitenant openshift cluster, and provide day 2 operation as well.

Thanks for your insight!

related to https://github.com/sorenmat/k8s-rds/issues/44

**Comment by linki** [comment]
Hi @pierreozoux,

thanks for your interest 😄

It's a private project and not used in any professional context afaik. Maintenance is best-effort and not actively pursued by me at the moment.

You already found [aws-service-operator](https://github.com/awslabs/aws-service-operator) which takes a slightly different approach (CRD for each AWS resource, e.g. an RDS instance) but is probably more active. It doesn't support RDS yet but there's an [issue you can upvote](https://github.com/awslabs/aws-service-operator/issues/39).
