### ISSUE TITLE
How to remove a stack created with cloudformation-operator ?

### ISSUE THREAD

**Issue by safaa-alnabulsi** [linki/cloudformation-operator#387]
Hi, can this be used to delete the stacks besides creating them? If so, can you please guide me?  I couldn't find anything online nor in this repo. 

That's how we create a stack and I would like to remove it when a speific condition is met.
```
&cloudformation.Stack{
		TypeMeta:   TypeMeta("cloudformation.linki.space/v1alpha1", "Stack"),
		ObjectMeta: i.objectMeta,
		Spec: cloudformation.StackSpec{
			Parameters: i.Parameters,
			Tags:       i.Tags,
			Template:   i.Template,
		},
	}
```

**Comment by linki** [comment]
When you remove the `Stack` resource from the cluster, it will try to delete the CloudFormation Stack, e.g. `kubectl delete stack <my-stack>`, see also https://github.com/linki/cloudformation-operator#delete-stack

**Comment by safaa-alnabulsi** [comment]
Thank you for replying. It seems I need to delete it in my code. This has nothing to do with your operator. 
But I was curious about the status of the created stack, it's set to empty string and not READY nor CREATED. 
```
status:
  outputs: null
  stackID: ""
```

**Comment by linki** [comment]
Check if the Stack was successfully created. If those fields are not populated after that, then it's probably a bug.

**Comment by safaa-alnabulsi** [comment]
Thank you for your support. I will close this ticket as my issue is resolved.
