### ISSUE TITLE
Use paginated API calls

### ISSUE THREAD

**Issue by linki** [linki/cloudformation-operator#4]

**Comment by mseiwald** [comment]
Hi @linki! We are considering using this operator. I didn't find any place where it should be using a paginated call, can you elaborate on that? Would you see any problems with using this operator at scale?

**Comment by linki** [comment]
@mseiwald The issue was relevant for an older version of this controller. I'm going to close it.

> Would you see any problems with using this operator at scale?

It's extremely basic, untested and mostly unused, so I wouldn't recommend to use it as is.

But it might be a good starting point if you desire its functionality. There have been other people showing interest and it could be worthwhile to collaborate on making it more useful.
